Feature/ms 5 statistics
anstylist/medical-site-fed pull request #2
Opened 2023-07-14 07:32 UTC by erickfabiandev

The creation of the responsive component "Statistics Section" was carried out.
I attach the interactive gif of the implementation carried out

![MS5](https://github.com/anstylist/medical-site-fed/assets/109047392/45c5a544-6057-469a-baba-75bf62de8bf1)

2023-07-14 17:49 UTC, jlvillegas04 approved these changes
Good job! Everything is working nicely and the code is clean.
As a reccomendation, I would suggest to write your code only in english. I see you have some props called `icono` and `simbol`, which could be changed to "icon" and "symbol" as to mantain coherence in our code. Other than that, I like your component a lot!

2023-07-14 20:43 UTC, andrystylist requested changes

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.scss
> +@import '../../styles/variables';
Erick, lo que me he documentado  en Sass se recomienda el uso del @use en vez de @import, lo que cambia es la manera de usarlo. ejemplo:

```scss
 font-family: variables.$font-open-sans;
```

te dejo el link de lo que te comento 
https://sass-lang.com/documentation/at-rules/import/

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.scss
> +        background: #3FB6D6 !important;
Erick, busca la manera de evitar los !important, con el uso de BEM  no es buena practica y evitamos que la especificidad nos obligue usar la sentencia importan!

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.scss
> +    @media (min-width:1024px) {
trata de aplicar mobile first, y poner los @media, a parte de los estilos por defecto que son mobile, es decir arriba los estilos y al final los media

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.jsx
> +    const{num, simbol, icono,text}=props
Creo que esto mejor lo podemos hacer al inicio de la función en lugar de crear unas constantes dentro del componente:

```jsx
const CardStatistics = ({num, symbol, icon, text}) => {
...
};
```
Por otra parte, creo que sería bueno siempre usar nombres de variables y funciones en inglés.

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.jsx
> +    const[count,setCount]=useState(0)
Veo que quizás no estás utilizando el linter que ya tenemos instalado en el proyecto. Éste lo pueden correr haciendo uso del siguiente comando en la raíz del proyecto:

Para ver los errores del linter:

```sh
npm run lint
```
Y para ver y hacer autofix de ellos:

```sh
npm run lint -- --fix
```

Les recomiendo a todos por otra parte instalar el plugin de VSCode ESLint y Sonar Lint para que mientras vayan programando éstos plugins nos muestren allí mismo los warnings y errores que no cumplan con la guía de estilos definida por el linter del proyecto.

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.jsx
> +        if(count<num){
Tener `if...else` anidados aumenta la complejidad cognitiva y la lectura del código, una manera de resolver éstos es haciendo uso de los early returns:

```js
if (!count<num) {
  return
}

...
```

https://levelup.gitconnected.com/javascript-refactoring-tips-reducing-function-complexity-22f4ad3f86cc

2023-07-14 20:43 UTC, andrystylist commented on src/components/CardStatistics/CardStatistics.jsx
> +    <div className='container__card'>
Creo que los nombres de las clases deberían ser un poco más específicos de tu componente, éste contenedor pudiera tener una clase llamada `statistics-card` o `statistics-card-container`. De hecho a modo de debug nos ayuda llamar a la clase principal de nuestro componente igual que el componente (`statistics-card`).

2023-07-14 20:50 UTC, andrystylist requested changes

2023-07-14 20:50 UTC, andrystylist commented on src/pages/App.jsx
> -      <Main />
Tratemos de no subir los cambios de  este archivo, porque lo usaremos todos mientras no definamos nuestras rutas, después definimos una tarea para integrar todos nuestros cambios , usamos este archivo a modo de prueba. yo dejé en el comentario donde hacer la prueba para que no crees otro Main, y deben hacer esas pruebas con ese Main para que no cree conflictos con sus estilos.

2023-07-14 20:54 UTC, andrystylist commented
Erick, me gusto demasiado tu resultado y me encanta los avances que estamos teniendo, espero que tomes en cuenta mis sugerencias para que nuestro proyecto se destaque aún más.  resaltando que nos gusta ser detallistas

2023-07-14 23:15 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.jsx
> +    const[count,setCount]=useState(0)
Se procedio con la modificacion y uso de ESLint para validar los linter

2023-07-14 23:16 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.jsx
> +    const{num, simbol, icono,text}=props
Se realizo el cambio solicitado.

2023-07-14 23:20 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.scss
> +@import '../../styles/variables';
Done !

2023-07-14 23:23 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.scss
> +        background: #3FB6D6 !important;
Done !

2023-07-14 23:28 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.scss
> +    @media (min-width:1024px) {
Corregido

2023-07-14 23:28 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.jsx
> +        if(count<num){
Done !

2023-07-14 23:37 UTC, erickfabiandev commented on src/components/CardStatistics/CardStatistics.jsx
> +    <div className='container__card'>
Modificado

2023-07-14 23:43 UTC, erickfabiandev commented
Se realizo todas las observacion, ya realice la actualizacion

2023-07-19 04:15 UTC, andrystylist approved these changes

2023-07-20 01:12 UTC, closed without merging