Feature/MS-3 Appointment Form
anstylist/medical-site-fed pull request #3
Opened 2023-07-14 17:46 UTC by jlvillegas04

The Appointment Form was created, with a basic structure for storing data. 
Below, I attach a gif of the different views of the component.

![Animation](https://github.com/anstylist/medical-site-fed/assets/132522021/ec8a60bf-af6e-44e6-9c24-bf72d1c56864)

2023-07-14 18:06 UTC, erickfabiandev approved these changes
Good work, approved changes. Let's keep working like this. 🎉

2023-07-14 18:37 UTC, andrystylist commented
Oye Juan Buen trabajo te dejo unas pequeñas observaciones que vi en el código

2023-07-14 18:55 UTC, andrystylist requested changes

2023-07-14 18:55 UTC, andrystylist commented on src/components/MS-3 Form/AppointmentForm.jsx
> +        <button onClick={handleFormSubmit}>Book appointment</button>
Por acá te recomendaría, colocar el type del button de forma explicita siempre , en este caso `type="submit"`

2023-07-14 18:55 UTC, andrystylist commented on src/components/MS-3 Form/AppointmentForm.scss
> +  span {
Recomendaría no aumentar la especificidad dando estilos a las etiquetas html, sería mejor aplicar BEM, en este caso ejemplo `main-banner-container__span`  pero usando Sass se abreviaría  el bloque asi `&__span`, esta recomendación te la hago para todos los estilos

2023-07-14 18:55 UTC, andrystylist commented on src/components/MS-3 Form/AppointmentForm.scss
> +      background-color: #3774d9;
para usar las variables globales puedes importarlas en tu inicio de tu archivo

```scss
@use '../../styles/variables';
```
y las usas asi ejemplo: 
```scss
color: variables.$footer-font-color;
```

2023-07-14 21:38 UTC, jlvillegas04 commented on src/components/MS-3 Form/AppointmentForm.jsx
> +        <button onClick={handleFormSubmit}>Book appointment</button>
Done!

2023-07-14 21:38 UTC, jlvillegas04 commented on src/components/MS-3 Form/AppointmentForm.scss
> +  span {
Done!

2023-07-19 04:17 UTC, andrystylist approved these changes

2023-07-19 22:29 UTC, erickfabiandev approved these changes
Done !

2023-07-19 22:30 UTC, merged